[project]
name="src"
version="0.0.1"
description="MLOPS DEMP Project"
authors=[{name="Nileh A", email="NileshA@gmail.com"}]

[tool.setuptools]
packages = {find= {}}

[tool.setuptools.dynamic]
dependencies={file="requirements.txt"}